apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-cluster-role
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
rules: 
- apiGroups: ["","apps"] 
  resources: ["nodes","pods","pods/log",deployments/scale]
  verbs: ["list","update","patch","create"]


