apiVersion: v1
kind: Pod
metadata:
  name: hs-pre
  labels:
    app: hs-pre
spec:
  containers:
  - name: hs-pre
    ports:
    - containerPort: 5000  
    image: hyeonseong0917/hs_pre:latest
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt
          
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: hyeonseong-nfs-pvc